/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as NosNiveauxRouteImport } from './routes/nos-niveaux'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as VieScolaireRouteImport } from './routes/vie-scolaire'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const NosNiveauxRoute = NosNiveauxRouteImport.update({
  id: '/nos-niveaux',
  path: '/nos-niveaux',
  getParentRoute: () => rootRouteImport,
} as any)
const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const VieScolaireRoute = VieScolaireRouteImport.update({
  id: '/vie-scolaire',
  path: '/vie-scolaire',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/galerie': typeof GalerieRoute
  '/nos-niveaux': typeof NosNiveauxRoute
  '/temoignages': typeof TemoignagesRoute
  '/transport': typeof TransportRoute
  '/vie-scolaire': typeof VieScolaireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/galerie': typeof GalerieRoute
  '/nos-niveaux': typeof NosNiveauxRoute
  '/temoignages': typeof TemoignagesRoute
  '/transport': typeof TransportRoute
  '/vie-scolaire': typeof VieScolaireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/galerie': typeof GalerieRoute
  '/nos-niveaux': typeof NosNiveauxRoute
  '/temoignages': typeof TemoignagesRoute
  '/transport': typeof TransportRoute
  '/vie-scolaire': typeof VieScolaireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/galerie'
    | '/nos-niveaux'
    | '/temoignages'
    | '/transport'
    | '/vie-scolaire'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/galerie'
    | '/nos-niveaux'
    | '/temoignages'
    | '/transport'
    | '/vie-scolaire'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/galerie'
    | '/nos-niveaux'
    | '/temoignages'
    | '/transport'
    | '/vie-scolaire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  GalerieRoute: typeof GalerieRoute
  NosNiveauxRoute: typeof NosNiveauxRoute
  TemoignagesRoute: typeof TemoignagesRoute
  TransportRoute: typeof TransportRoute
  VieScolaireRoute: typeof VieScolaireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nos-niveaux': {
      id: '/nos-niveaux'
      path: '/nos-niveaux'
      fullPath: '/nos-niveaux'
      preLoaderRoute: typeof NosNiveauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vie-scolaire': {
      id: '/vie-scolaire'
      path: '/vie-scolaire'
      fullPath: '/vie-scolaire'
      preLoaderRoute: typeof VieScolaireRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  GalerieRoute: GalerieRoute,
  NosNiveauxRoute: NosNiveauxRoute,
  TemoignagesRoute: TemoignagesRoute,
  TransportRoute: TransportRoute,
  VieScolaireRoute: VieScolaireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
