/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as NosNiveauxRouteImport } from './routes/nos-niveaux'
import { Route as VieScolaireRouteImport } from './routes/vie-scolaire'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const NosNiveauxRoute = NosNiveauxRouteImport.update({
  id: '/nos-niveaux',
  path: '/nos-niveaux',
  getParentRoute: () => rootRouteImport,
} as any)
const VieScolaireRoute = VieScolaireRouteImport.update({
  id: '/vie-scolaire',
  path: '/vie-scolaire',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/nos-niveaux': typeof NosNiveauxRoute
  '/vie-scolaire': typeof VieScolaireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/nos-niveaux': typeof NosNiveauxRoute
  '/vie-scolaire': typeof VieScolaireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/nos-niveaux': typeof NosNiveauxRoute
  '/vie-scolaire': typeof VieScolaireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/a-propos' | '/nos-niveaux' | '/vie-scolaire'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/a-propos' | '/nos-niveaux' | '/vie-scolaire'
  id: '__root__' | '/' | '/a-propos' | '/nos-niveaux' | '/vie-scolaire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  NosNiveauxRoute: typeof NosNiveauxRoute
  VieScolaireRoute: typeof VieScolaireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nos-niveaux': {
      id: '/nos-niveaux'
      path: '/nos-niveaux'
      fullPath: '/nos-niveaux'
      preLoaderRoute: typeof NosNiveauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vie-scolaire': {
      id: '/vie-scolaire'
      path: '/vie-scolaire'
      fullPath: '/vie-scolaire'
      preLoaderRoute: typeof VieScolaireRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  NosNiveauxRoute: NosNiveauxRoute,
  VieScolaireRoute: VieScolaireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
